### PR TITLE
Add InvertedRangeSlider

### LINKED ISSUE #440: HSV Hue Should be invertible
You should be able to invert the hue value selection from within GRIP.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #440 

WIP.  Feel free to play.
This solution was provided in the [Bitbucket Issue](https://bitbucket.org/controlsfx/controlsfx/issues/683/invertible-rangeslider). 
Things to do:
- Fix the styling (right now it looks a little weird)
- Save if it is inverted to XML
- Handle inverted in core
- Add a way to disable inverting
- Documentation

untitled

### CODE REVIEW

**Comment by SamCarlberg** [comment]
Might want to leave a link to the bitbucket issue

**Comment by SamCarlberg** [comment]
Also, you can still see a blue stripe on the bottom of the track between the two sliders

**Comment by AustinShalit** [comment]
Yup.  That is what I meant when I said 

> Fix the styling (right now it looks a little weird)

**Comment by AustinShalit** [comment]
I am going to close this PR because it does not look like this is going to happen in the near future. Please reopen if you have new information.

**Pull request closed without merging**
