### PR TITLE
Update CONTRIBUTING.md with info about author tag

### LINKED ISSUE #665: Add information about authorship annotation to contributing markdown
> # Putting Your Name in Source Code Files
> *(a.k.a., the “Author Tags” Issue)*

> Everyone wants to get credit for work they do, from the artist 
who signs her painting to the author who puts her name on the
spine of her book or the top of her blog. It’s human nature to crave
recognition in one way or another, but littering source files with
your name is, in our opinion, more trouble than it’s worth. We’ve
all seen these attributions at the top of source files, nestled snugly
against the copyright declarations:
```
————————————---—————————————————
Created: October 1998 by Brian W. Fitzpatrick <fitz@red-bean.com>
————————---—————————————————————
```
The tradition of putting your name at the top of your source code
is an old one (heck, both of us have done it in the past), and may
have been appropriate in an age where programs were written by
individuals and not teams. Today, however, many people may touch
a particular piece of code, and the issue of name attribution in a file
is the cause of much discussion, wasted time, and hurt feelings. As a
result, we advocate strongly against names as a sign of ownership in
source code files (at best, include a name to designate a first choice 
to review any changes you might make to the file, but be careful
that you don’t imply ownership).
Let’s imagine, for example, that you create a new file in your team’s
project—you write a few hundred lines of code, smack your name
and the appropriate copyright header at the top of the file and send
it off for code review, and later, commit it to the repository. No
problems, no drama, no disagreements so far. Let’s say that your
teammate Adrian comes along and makes some changes to the file:
at what point does he get to put his name at the top of the file? Does
he have to fix a bug? Five bugs? Does he have to write a function?
Two functions? How many lines of code does he have to write?
What if he writes a function, slaps his name on the file, and then
someone else comes along and rewrites “his” function? Does this
person now get to put her name on the file? Does she get to take
Adrian’s name off? Unlike other collaborative pieces of creative
work—plays, novels, films—software keeps changing even after it’s
“done.” So, while listing contributor credits at the end of a movie is
a safe and static thing, attempting to add and remove names from a
source file is a never-ending exercise in insanity.
Certainly you can answer all these questions and extensively
document every possible edge case, but maintaining this, tracking
it, and keeping an eye out for violations is an incredible waste of
time—time that could be spent actually writing code. It’s for this
very reason that we advocate tracking credit at the project level, 
not in the code itself. If you need more detail, your version control
system can tell you. All those moments will be lost in time, like tears
in rain.
\- Team Geek: A Software Developer's Guide to Working Well with Others, Brian Fitzpatrick, Ben Collins-Sussman

### PR DESCRIPTION
**Pull request by SamCarlberg**
Closes #665

### CODE REVIEW

**Comment by AustinShalit** [comment]
We should probably copy the ¶ from wpilib about why we don't use the author tag

**Comment by JLLeitschuh** [comment]
What is the paragraph in WPI Lib? Can you paste it here so we can all see it?

**Comment by AustinShalit** [comment]
I can't seem to find it right now.

**Comment by AustinShalit** [comment]
LGTM

**Comment by SamCarlberg** [comment]
@JLLeitschuh Can you add something from Team Geek about this? You've pretty much taken it to heart

**Comment by AustinShalit** [comment]
This is GTG

**Pull request merged**
