### PR TITLE
Fix issue #744, related to failed code generation with contours

### PR DESCRIPTION
**Pull request by phurley**
Addresses issue #744, which I almost certainly caused :-(

[//]: # (Please ensure that the "Allow edits from maintainers" checkbox is checked. Thanks!)

### CODE REVIEW

**Comment by phurley** [comment]
Wrote a script to look for other issues, turned up a couple which, are fixed in my second commit. Sorry about missing these the first time around. I am automating a GRIP to RaspberryPi process and will keep testing missing issues.

**Comment by JLLeitschuh** [comment]
Okay, let us know when you want us to review this fully. Thank you for the PR!

**Comment by SamCarlberg** [comment]
@phurley have you found any other missing namespace qualifiers? I'd like to have this merged soon.

**Comment by phurley** [comment]
@SamCarlberg I have not. I did have a couple issues with header files (opencv 2 vs 3?) when building on a raspberry pi, but none on my mac or windows box. Regardless I do not believe that is a namespace issue, so I would say merge away.

**Comment by SamCarlberg** [comment]
Okay, thanks for doing this!

**Pull request merged**
