### PR TITLE
Makes deployer deploy to grip-core.jar

### LINKED ISSUE #305: Deployed GRIP jar should be called "grip.jar"
This makes it possible to run GRIP automatically from a C++ or Java robot program.  Currently, you'd have to know the exact version of GRIP that was deployed.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
The deployer now coppies and renames the core grip jar to
`grip-core.jar` and SCPs that file over every time instead of
coping the original source code.

Closes #305

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Yes, I did test this on gears bot. It works.

**Comment by ThomasJClark** [comment]
Why would we make another local copy of the jar?  We just want the copy on the roboRIO to be named grip.jar, not the local one

**Comment by ThomasJClark** [comment]
Also, it should probably be grip.jar and not grip-core.jar

**Comment by JLLeitschuh** [comment]
I can't do that with the ant SCP tool.
I have to copy it. Unless you have some other way you know how to SCP a file while changing its name.

**Comment by JLLeitschuh** [comment]
By the way, I tried using some of these other params: https://ant.apache.org/manual/Tasks/scp.html
Didn't work.

**Comment by ThomasJClark** [comment]
`localTofile` does't work?

**Comment by JLLeitschuh** [comment]
No, throws a builder exception

**Comment by ThomasJClark** [comment]
Ok, then `mv` the file with an ssh command after uploading it

**Comment by JLLeitschuh** [comment]
Why? The temporary directory automatically gets cleaned up by java when we're done with it.
I've seen the `mv` command block before and never return on my computer.

Why is this any worse?

**Comment by ThomasJClark** [comment]
Because you're using up extra space on the user's computer to store a file that's already on there.  It's probably not *that* much space, but it just seems like an incredibly hacky way to change an SCP target.

If you've really done every thing you can to investigate how to do this for real, I guess we can accept this workaround as a necessary evil.  Make sure you change the "-core" thing, though

**Comment by JLLeitschuh** [comment]
Okay, fixed to remove the `-core`

**Pull request merged**
