### PR TITLE
Add Launcher Binary

### LINKED ISSUE #345: Linux not working with Maven Network Tables
When trying to run GRIP after an Ubuntu install it doesn't work (nothing happens). Then if I go to /opt/GRIP where it installed and run GRIP I get this:

parallels@ubuntu:/opt/GRIP$ ./GRIP
Jan 10, 2016 1:04:04 PM java.util.logging.LogManager$RootLogger log
CONFIG: Configuration done.
platform: /Linux/amd64/
Exception in Application start method
GRIP Error invoking method.
GRIP Failed to launch JVM

parallels@ubuntu:/opt/GRIP$ java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b05)
OpenJDK 64-Bit Server VM (build 25.72-b05, mixed mode)
parallels@ubuntu:/opt/GRIP$ ^C
parallels@ubuntu:/opt/GRIP$

### LINKED ISSUE #370: Windows Server 2008 R2 Support
I'm having an issue running GRIP 1.0.0 on my Windows machine.
I am running Java JDK 8u66 (x64) on Windows Server 2008 R2 (which is practically Win7).

When I launch GRIP, I get a message that says `Error invoking method.`
After hitting OK, I get a message that says `Failed to launch JVM`

### LINKED ISSUE #566: Cannot launch GRIP through .deb package - Linux
GRIP runs fine if started via gradlew, however running GRIP through the Linux ".deb" file there is an error thrown:

```
Apr 11, 2016 8:43:53 PM java.util.logging.LogManager$RootLogger log
CONFIG: Configuration done.
Apr 11, 2016 8:43:53 PM java.util.logging.LogManager$RootLogger log
CONFIG: GRIP Version: 1.4.0
platform: /Linux/amd64/
terminate called after thowing an instance of 'std::system_error
   what():  Enable multithreading to use std::thread: Operation not permitted
Aborted
```

I can't seem to find kernel logs dumped anywhere on the OS either other than GRIP.log which returns "FINE:" up until the system begins to "load singletons" which says 6ms then no logs after that.

~~[GRIP.log](https://drive.google.com/open?id=0B86Py5WkgumYTmFNeFJBOUNGbUU)~~

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #566 
closes #345 
closes #370 

This solves the Linux build issues!

Thank you @PeterJohnson and @FibreFoX for your work on this.

### CODE REVIEW

**Comment by AustinShalit** [comment]
This needs a little more work.  Will be ready soon.

**Comment by PeterJohnson** [comment]
Do you really want to include the raw launcher binary?  Is this binary identical for x86 and x64?  Wondering why we aren't building it from source...

**Comment by AustinShalit** [comment]
Yea... going to fix that

**Comment by AustinShalit** [comment]
Can someone please check my work on this.  A known issue is RPM builds fail right now.

**Pull request merged**
