### PR TITLE
Allows Webcam Sources to be removed

### LINKED ISSUE #80: Can't Remove WebcamSource
It is impossible to remove a webcam source.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Webcameras can now be removed when the delete button is pressed.

Closes #80

### CODE REVIEW

**Comment by ThomasJClark** [comment]
`Pipeline::onSourceRemoved` should unregister the source from the event bus.  Besides that, this is good

**Comment by JLLeitschuh** [comment]
That doesn't work. If the source is unregistered before the event is passed off to it the it will never be removed.
I'll have to do it inside of the source.

**Comment by JLLeitschuh** [comment]
Resolved

**Comment by ThomasJClark** [comment]
Ok, makes sense.  Now that I think about it, it would probably make sense for `Step`, `Connection`, etc, to also similarly unregister themselves instead of having `Pipeline` do it.  Single responsibility and encapsulation and such.

**Pull request merged**
