### PR TITLE
Fix std::thread thing on linux by vendoring NetworkTables

### PR DESCRIPTION
**Pull request by ThomasJClark**
For some reason, manually building ntcore.so fixes it

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Fails on travis anyways. Should we wait for them to update NetworkTables and just use that??

**Comment by ThadHouse** [comment]
What's the bug that's happening with ntcore and std::thread?

**Comment by ThomasJClark** [comment]
ntcore was crashing on linux, but only in a packaged binary (running from gradle works fine).  I think this is because it's built without `-pthread`.  Running from gradle is ok because java must already link with pthread, but in the packaged JVM that JavaFX puts together, it doesn't work.

Rebuilding networktables on my machine and manually using it as the dependency for linux builds also works.  I think this is because newer versions of GCC don't require `-pthread`.

**Comment by JLLeitschuh** [comment]
Can you resolve this before you leave @ThomasJClark
I want to be able to build releases myself and I don't have an Ubuntu OS to do so currently.

**Comment by AustinShalit** [comment]
This was solved by the ntcore team. Closing the PR because it is no longer needed.

**Pull request closed without merging**
