### PR TITLE
Make the preloader have a fancy background

### PR DESCRIPTION
**Pull request by SamCarlberg**
Remove the progress bar from the preloader as well

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
For documentational purposes can you include a GIF or a screen shot?

**Comment by JLLeitschuh** [comment]
Make sure the tests are working and then let me know when this works.

**Comment by JLLeitschuh** [comment]
This looks like the tests passed. Is this good to be merged?

**Comment by SamCarlberg** [comment]
It has been for over a month

**Comment by AustinShalit** [comment]
I know we just merged this but I am finding it hard to read "GRIP" on the new loader.  Should we lighten up the logo?

**Pull request merged**
