### PR TITLE
Fix save dialog not appearing when closing an edited project

### LINKED ISSUE #660: ⌘Q -> Cancel still quits GRIP
Using the shortcut ⌘Q and pressing cancel on the dialog still quits GRIP when it should just close the dialog.

### LINKED ISSUE #688: Closing the UI window doesn't prompt to save
Probably related to #660.

Hitting the close button, closing from the taskbar, and pressing the "close window" shortcut on my laptop all close without prompting to save.

However, `File -> Exit` _does_ prompt to save

### PR DESCRIPTION
**Pull request by SamCarlberg**
Closes #660
Closes #688

### CODE REVIEW

**Comment by AustinShalit** [comment]
When using ⌘Q I need to click twice on the cancel button.  I think it opens 2 dialogs and I need to click cancel on both.

**Comment by SamCarlberg** [comment]
Can you move the confirmation dialog away from the default location and see if two were created, or if a second one appears after you hit cancel?

**Comment by AustinShalit** [comment]
It appears after I hit cancel.  Also for some reason the second one highlights the yes button.

**Comment by SamCarlberg** [comment]
The "Yes" option is selected by default. It's weird how it creates a second one, though

**Comment by JLLeitschuh** [comment]
This good to go?

**Comment by AustinShalit** [comment]
No

**Comment by SamCarlberg** [comment]
I'm moving this to v1.5.1 because this isn't a critical patch

**Comment by SamCarlberg** [comment]
Can someone with a Mac try to figure out why two dialogs appear? @JLLeitschuh @AustinShalit

**Comment by AustinShalit** [comment]
The first dialog's trace:
```
Dec 29, 2016 10:52:05 AM edu.wpi.grip.ui.MainWindowController showConfirmationDialogAndWait
SEVERE: showConfirmationDialogAndWait
java.lang.Throwable
	at edu.wpi.grip.ui.MainWindowController.showConfirmationDialogAndWait(MainWindowController.java:117)
	at edu.wpi.grip.ui.MainWindowController.quit(MainWindowController.java:259)
	at edu.wpi.grip.ui.MainWindowController.lambda$null$1(MainWindowController.java:103)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassStage.lambda$requestClosingAllWindows$305(GlassStage.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassStage.requestClosingAllWindows(GlassStage.java:196)
	at com.sun.javafx.tk.quantum.QuantumToolkit$2.handleQuitAction(QuantumToolkit.java:331)
	at com.sun.glass.ui.mac.MacApplication$4.action(MacApplication.java:165)
```

The second dialog's trace:
```
Dec 29, 2016 10:52:09 AM edu.wpi.grip.ui.MainWindowController showConfirmationDialogAndWait
SEVERE: showConfirmationDialogAndWait
java.lang.Throwable
	at edu.wpi.grip.ui.MainWindowController.showConfirmationDialogAndWait(MainWindowController.java:117)
	at edu.wpi.grip.ui.MainWindowController.quit(MainWindowController.java:259)
	at edu.wpi.grip.ui.MainWindowController.lambda$null$1(MainWindowController.java:103)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:121)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:150)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:148)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1174)
```

**Comment by SamCarlberg** [comment]
Interesting. On Windows, this is the stack trace (only one dialog appears):

```
java.lang.Throwable: showConfirmationDialogAndWait
	at edu.wpi.grip.ui.MainWindowController.showConfirmationDialogAndWait(MainWindowController.java:117)
	at edu.wpi.grip.ui.MainWindowController.quit(MainWindowController.java:259)
	at edu.wpi.grip.ui.MainWindowController.lambda$null$1(MainWindowController.java:103)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:121)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:150)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:148)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1174)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SamCarlberg** [comment]
@AustinShalit, does the same thing happen with `⌘-Q`, `⌘-W`, and just clicking the close button?

**Comment by AustinShalit** [comment]
`⌘-W` is not a shortcut.  When clicking the close button this does not happen.

**Comment by SamCarlberg** [comment]
Okay, so closing the app on OSX will also trigger a window close request. I guess we'll need to check what caused the event and only do something when it's from `com.sun.glass.ui.Window.notifyClose`

Can you put a debug point on line 103 (the `if (!quit())` line in the window close handler) and see what the source of the event is? We might be able to use that.

**Comment by AustinShalit** [comment]
I opened https://github.com/SamCarlberg/GRIP/pull/6 to solve this issue.

**Comment by AustinShalit** [comment]
Updated https://github.com/SamCarlberg/GRIP/pull/6

**Pull request merged**
