### PR TITLE
Added an "About" dialog.

### PR DESCRIPTION
**Pull request by AdamuKaapan**
I decided to go ahead and do a simple about dialog to try and tackle issue #439 (I wanted to try and contribute, and that seemed like an easy place to start that wouldn't mess with too much). Slight disclaimer, I don't know anything about FXML or the conventions/structure of this project: I derived what I can from what I saw (mainly in the settings dialog), but this may be entirely different than what you want/need.

Also, a slight introduction. My name is Adam, I'm a Java programmer with FRC Team 3268, the Valhallabots. I'm beginning to be very interested in vision processing (both in and out of FRC), and I'm hoping to maybe contribute to this project in my spare time, even if it's just small random things like this.

Thanks for making this awesome project, I'm looking forwards to hopefully using it this year!

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
New About Dialog

I'd love to see the logo in the about as well.
I think the about should be under another menu separate from "Tools" probably a menu like "Help". @ThomasJClark What do you think?

This is what the "About" screen looks for on Mac and I'd like to see it look more like this.
Mac About Screen

**Comment by AdamuKaapan** [comment]
Alright, I'll go ahead and do that. Good idea!

**Comment by AdamuKaapan** [comment]
Does that seem better?

**Comment by JLLeitschuh** [comment]
Can you upload a screenshot?

**Comment by ThomasJClark** [comment]
Clicking the hyperlinks just seems to freeze the application up.  Can you use `hostServices.showDocument()`?

**Comment by AdamuKaapan** [comment]
Here's a screenshot: https://gyazo.com/ec9100830ae8d9202b3ae08015a4054d

**Comment by AdamuKaapan** [comment]
As far as using HostServices, I don't see a way to get the instance of the Application unless you already have one set up? I could probably get one by adding a static variable somewhere or passing it through a few layers of menus? I'm not sure why those links are hanging... I'm on Windows 10 64-bit w/ Java 1.8.0_60 in case that's relevant. Is there anything in the console when you use the link?

**Comment by ThomasJClark** [comment]
It would probably be a good idea to allow access to the `Main` instance, since it's a singleton anyways.  So, you could do `Main.getInstance().getHostServices().showDocument(...)`.

**Comment by AdamuKaapan** [comment]
Should I do that or leave that to you guys?

**Comment by AdamuKaapan** [comment]
I'll just push what I did: see if that works.

**Comment by AdamuKaapan** [comment]
Any updates on whether this works or not?

**Comment by JLLeitschuh** [comment]
@ThomasJClark Says it looks small on Hi-DIP screens. He said he'll include a screenshot later.

**Comment by JLLeitschuh** [comment]
Resolved by #588

**Pull request closed without merging**
