### PR TITLE
Discourage use of the deploy tool

### PR DESCRIPTION
**Pull request by SamCarlberg**
An alert will show every time, even in the same session, for maximum annoyance

### CODE REVIEW

**Comment by AustinShalit** [comment]
When this is merged.  Lets close all deploy issues.  https://github.com/WPIRoboticsProjects/GRIP/labels/deploy

**Comment by JLLeitschuh** [comment]
I disagree with the decision of removing the tool.
@EdWard680 Don't people rely upon it for deploying grip to a PI?
Does code gen work on a PI just as fast?

**Comment by SamCarlberg** [comment]
> I disagree with the decision of removing the tool.

We're not removing it, just showing an alert that discourages its use because code generation is the better solution.

> Does code gen work on a PI just as fast?

Do you mean, "does the generated code run just as fast as GRIP?" or "is the workflow just as fast for using generated code as it is for deploying GRIP?"

**Comment by EdWard680** [comment]
@JLLeitschuh I would agree that code-gen should be encouraged, and the tool currently doesn't do anything with code-gen, however I don't think this should be a deprecation of the concept of a full "deploy." I think teams would find the most use from a modified deploy tool which deploys an executable/script built from grip code gen, but until something like that were to be made, this seems like a good deprecation.

**Comment by AustinShalit** [comment]
@bradamiller Thoughts on this?

**Pull request merged**
