### PR TITLE
Publish core jar

### LINKED ISSUE #787: Release core.jar as a separate release
We will need to have one per OS because we only include the library for the OS we are building on.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #787

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
You need to do the same thing for windows given that our shadow jar doesn't include binaries for all OS'es.

Maybe we could create a jar that contains all of them. That should be pretty easy with gradle.

But in the short term @AustinShalit can you add a config change to the appveyor script too?

**Comment by JLLeitschuh** [comment]
@AustinShalit can you take care of this?

**Comment by JLLeitschuh** [comment]
Does this work on windows? Just checking. Its fine if you haven't tested it.

**Comment by AustinShalit** [comment]
Hold off.  Still testing

**Comment by JLLeitschuh** [comment]
Status?

**Comment by AustinShalit** [comment]
Broken

**Pull request closed without merging**
