### PR TITLE
Fix UI tests on Azure

### PR DESCRIPTION
**Pull request by SamCarlberg**
Switch to Linux for running the UI tests
Install OpenJFX and openjdk through `apt`

### CODE REVIEW

**Comment by SamCarlberg** [comment]
@JLLeitschuh Thoughts on why the code coverage dropped so much?

**Comment by JLLeitschuh** [comment]
No idea. This doesn't seem like the kind of thing that would cause it. Perhaps there is binary jacoco comparison going on?

**Comment by SamCarlberg** [comment]
I think it _might_ be because there was no coverage report for the latest commit on master. I'm not sure, though

**Comment by SamCarlberg** [comment]
Oh, the UI tests aren't running because Java 11 is being used instead of Java 8 :man_facepalming:

**Comment by SamCarlberg** [comment]
ZuluFX is an OpenJDK + OpenJFX build provided by Azul Systems (https://www.azul.com/). We used the embedded Zulu JRE on the RoboRIO for the 2018 FRC season

**Pull request merged**
