### PR TITLE
Implemented a workaround to fix issue # 252.

### PR DESCRIPTION
**Pull request by PaulaRudy**
Now all save files will save with the previews closed. This fixes 252 by ensuring the race condition caused when desaturate and another operation's previews are opened at the same time.

Closes issue #252

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
@ThomasJClark you did serialization, I'm going to leave this one to you to verify.

**Comment by JLLeitschuh** [comment]
Actually, @PaulaRudy couldn't you just change line 121 of the `Socket Converter` so that set previewed was always set to false?

**Comment by ThomasJClark** [comment]
Yeah, this is not okay. Do what @JLLeitschuh said,  and also open an issue to find the underlying problem.

**Comment by ThomasJClark** [comment]
Also, I think there are tests for this functionality. If we decide to intentionally disable it for now, we should disable the tests also.

**Comment by PaulaRudy** [comment]
So apparently this doesn't actually prevent the error all the time- I've discovered that when GRIP is slowed down (for whatever reason)  it's possible to trigger the bug by manually pressing the preview buttons. I have the changes y'all have prescribed implemented on my local branch, but I haven't pushed yet because I'm trying to see if I can fix the issue entirely. Do you think this is a good idea to implement in the mean time? It won't fix things, but it will help prevent them.

**Pull request closed without merging**
