### PR TITLE
Update Gradle to v3.0

### LINKED ISSUE #663: Update to Grade 3.0
There is a new release of Grade that we should update too.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #663 

[Release Notes](https://docs.gradle.org/3.0/release-notes)

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Something don' be broke here

**Comment by AustinShalit** [comment]
All fixed.  PMD was updated with gradle...

**Comment by JLLeitschuh** [comment]
LGTM!

**Comment by JLLeitschuh** [comment]
Wait... Hold on. Why did codecov not report on this PR? Did the codecov stuff get published??

**Comment by JLLeitschuh** [comment]
Okay, looks like it still uploaded. Codecov just decided to be derpy.

**Comment by SamCarlberg** [comment]
Probably because @AustinShalit is amending commits

**Pull request merged**
