### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by ZeusChops**
Updating videoinput, opencv, javacv, gson, and jetty-server.
There is currently an issue with USB camera input dying after 3+ minutes (at least, it happens on my Mac).

### CODE REVIEW

**Comment by ZeusChops** [comment]
Exception log: http://pastebin.com/vKB7F73t

Log after GRIP crashes during grabber service being used for ~2 minutes then dying.

**Comment by JLLeitschuh** [comment]
Uhhhhhh.... Search here: https://github.com/bytedeco/javacv/issues

**Comment by ZeusChops** [comment]
Appears to be specifically an issue with Mac OS X. The exception doesn't show up while running Linux. Will be retesting with FFmpeg instead later today (hopefully OpenCV can be replaced with FFmpeg and not crash while on linux). Currently sorting out issues with an exception:

```
Aug 05, 2016 1:13:37 PM edu.wpi.grip.core.util.service.LoggingListener failed
SEVERE: [CameraSource] Failed from: STARTING
edu.wpi.grip.core.sources.GrabberService$GrabberServiceException: [Webcam 0] Failed to start
        at edu.wpi.grip.core.sources.GrabberService.startUp(GrabberService.java:55)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:54)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "/dev/video0". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:437)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)
        at edu.wpi.grip.core.sources.GrabberService.startUp(GrabberService.java:53)
        ... 3 more

Aug 05, 2016 1:13:37 PM edu.wpi.grip.core.util.service.LoggingListener starting
INFO: [CameraSource] Starting
[AVFoundation input device @ 0x7f948281abe0] Video device not found
```

**Comment by AustinBennett** [comment]
Exception occurred on Windows 10 while trying to run with current data (need to fix this, too):
```
Aug 05, 2016 11:46:40 PM edu.wpi.grip.util.service.LoggingListener starting
INFO: [CameraSource] Starting
Aug 05, 2016 11:46:40 PM edu.wpi.grip.util.service.LoggingListener failed
SEVERE: [CameraSource] Failed from: STARTING
edu.wpi.grip.core.sources.GrabberService$GrabberServiceException: [Webcam 0] Failed to start
         at edu.wpi.grip.core.sources.GrabberService.startUp(GrabberService.java:55)
         at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:54)
         at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
         at java.lang.Thread.run(Thread.java:745)
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: videoInput.setupDevice() Error: Could not setup device.
          at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:111)
          at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:101)
          at edu.wpi.grip.core.sources.GrabberService.startUp(GrabberService.java:53)
          . . . 3 more
```

I should probably compare this to the exception currently found on OS X while running Camera 0 on the same device.

**Comment by ZeusChops** [comment]
Windows 10 (Pro 64-bit, anniversary update - build 14393) checks out with current 619 branch, if the hardware appears to run without issues. Windows 8.1 & 7 need testing, and macOS needs fixing (FFMPEG-related errors).

**Comment by JLLeitschuh** [comment]
Is this done? Up to date? Working?

**Comment by ZeusChops** [comment]
Up to date, yes. Working, nope.

**Comment by ZeusChops** [comment]
Yay, deadlocking issue. Setup [Camera Source] -> [Resize Operation] -> [Find Lines] -> [Filter Lines] then stop the Camera source, now it may be deadlocked (or spam terminal/cmd/powershell with `Warning: POTENTIAL DEADLOCK`)

**Comment by SamCarlberg** [comment]
Open the GRIP process in VisualVM and do a thread dump, you'll be able to see what the threads are blocking on

**Pull request closed without merging**
