### PR TITLE
Fixes the DPI Scaling on the Deployment UI

### LINKED ISSUE #257: The deploy window is tiny
You need to copy the styles and stylesheet from the parent window

deploy

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #257

### CODE REVIEW

**Comment by ThomasJClark** [comment]
It's still tiny for me.

tiny

**Comment by JLLeitschuh** [comment]
Are you sure you had this pulled down? It got much bigger for me.

**Comment by JLLeitschuh** [comment]
Do you have any idea why this didn't work?

**Comment by ThomasJClark** [comment]
Try applying the style/stylesheets to `deployerController.getRoot()` instead of `dialog.getDialogPane()`

**Comment by JLLeitschuh** [comment]
Good thought. Thanks, will fix.

**Comment by ThomasJClark** [comment]
message

**Comment by JLLeitschuh** [comment]
@ThomasJClark Can you try this now?

**Comment by ThomasJClark** [comment]
It looks basically the same.

The title of the window should also probably not be "message"

**Comment by JLLeitschuh** [comment]
Merged Toms PR. I'm approving his PR by merging my own PR.

**Comment by ThomasJClark** [comment]
That's fine I guess. So you're gonna fix the "Message" thing in another PR, or do you think it should stay that way?

**Pull request merged**
