### PR TITLE
Fix webcam sources failing to stop when opening saved projects

### LINKED ISSUE #683: Opening a saved project while a webcam is running doesn't always release the webcam
Definitely introduced in e642cdc.

This looks like it's platform-specific; @JLLeitschuh isn't experiencing it on OS X Sierra.

### PR DESCRIPTION
**Pull request by SamCarlberg**
[//]: # (Please ensure that the "Allow edits from maintainers" checkbox is checked. Thanks!)

Closes #683

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I remember having a debate with Tom about this. I think that's what I had originally but he convinced me to move it out.
Can you leave a comment regarding why using this vs the other one causes this deadlock.

**Comment by SamCarlberg** [comment]
Code comment or GitHub comment?

**Comment by JLLeitschuh** [comment]
Comment in the code.

**Comment by JLLeitschuh** [comment]
LGTM!

**Pull request merged**
