### PR TITLE
Release converted images in GrabberService after they're no longer used

### PR DESCRIPTION
**Pull request by SamCarlberg**
Helps relieve some memory pressure.
Could help #783

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
The frame grabber writes memory into the same mat every read. Look at the Webcam frame grabber.

This will break something.

**Comment by JLLeitschuh** [comment]
Looking at the tests... It seems that it did break something.

**Comment by SamCarlberg** [comment]
It only breaks the tests though, it works fine in the real world. Would probably have to compare the frames to see if a change was made

**Comment by SamCarlberg** [comment]
I'm going to scrap this for the time being

**Pull request closed without merging**
