### PR TITLE
File extension

### PR DESCRIPTION
**Pull request by AustinShalit**
This should solve #263.  When saving a file that does not exist, the user is forced to save with the extension '.grip'.  The open file dialog limits the selection to '.grip' files with the option to allow all files.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Does force the user to append the .grip extension to the end or will it add it automatically if you don't?

**Comment by AustinShalit** [comment]
On OS X it defaults to this:


If I click save the program saves a file called "Untitled.grip".
When I delete the .grip extension and click save the program saves a file called "Untitled.grip".

**Comment by JLLeitschuh** [comment]
Cool! That's what we want!

**Comment by JLLeitschuh** [comment]
Waiting on @JacisNonsense to test this out on a Windows machine before we merge it.

**Comment by AustinShalit** [comment]
I just tested this on Windows 7 (dug an old laptop out of the closet).  Works identically to OS X.

**Pull request merged**
