### PR TITLE
Fixes Versioning breaking with leading v

### PR DESCRIPTION
**Pull request by JLLeitschuh**

### CODE REVIEW

**Comment by ThomasJClark** [comment]
What about if the tag ends with "-rc1" or something?

What about non-tagged commits, where it appends part of the hash?

**Comment by JLLeitschuh** [comment]
Those will work fine. Remember when we did the pre-release builds. Those build with no problem on linux.

**Comment by JLLeitschuh** [comment]
Also, for developers having the commit hash will give us the right commit to pull to put any stack traces in context.

**Comment by ThomasJClark** [comment]
They won't work, I literally just tested this.

**Pull request merged**
