### PR TITLE
Solve ordering issue when opening a file via command line

### LINKED ISSUE #670: I can No longer auto launch the Grip app and load a pipeline
With the latest update I can no longer Auto launch the Grip app on the Kangaroo with our pipe line the shortcut is  C:\Users\apple\AppData\Local\GRIP\GRIP.exe "C:\Users\apple\Documents\FRC GRIP FILES\Test.grip"

Do I have the shortcut wrong? I did recreate the pipe line because the new version would not open the old file.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #670

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
You tested this? If yes then LGTM!

**Comment by AustinShalit** [comment]
Yup.  Tested and it is good.

**Comment by JLLeitschuh** [comment]
LGTM!

**Comment by AustinShalit** [comment]
pullapprove is broken

**Comment by JLLeitschuh** [comment]
I'm chatting with someone there right now.

**Pull request merged**
