### PR TITLE
Feat/stereo bit map operation

### PR DESCRIPTION
**Pull request by JLLeitschuh**
tsukuba_l
tsukuba_r

``` xml
<grip:Pipeline>
  <sources>
    <grip:ImageFile>
      <property name="path" value="/Users/jonathanleitschuh/git_repos/MQP/GRIP_my_samples/tsukuba_l.png"/>
    </grip:ImageFile>
    <grip:ImageFile>
      <property name="path" value="/Users/jonathanleitschuh/git_repos/MQP/GRIP_my_samples/tsukuba_r.png"/>
    </grip:ImageFile>
  </sources>
  <steps>
    <grip:Step name="Desaturate">
      <grip:Input step="0" socket="0"/>
      <grip:Output step="0" socket="0" previewed="true"/>
    </grip:Step>
    <grip:Step name="Desaturate">
      <grip:Input step="1" socket="0"/>
      <grip:Output step="1" socket="0" previewed="false"/>
    </grip:Step>
    <grip:Step name="Stereo Bit Map">
      <grip:Input step="2" socket="0"/>
      <grip:Input step="2" socket="1"/>
      <grip:Input step="2" socket="2">
        <value>16.0</value>
      </grip:Input>
      <grip:Input step="2" socket="3">
        <value>19.0</value>
      </grip:Input>
      <grip:Input step="2" socket="4">
        <value>XSOBEL</value>
      </grip:Input>
      <grip:Output step="2" socket="0" previewed="true"/>
    </grip:Step>
  </steps>
  <connections>
    <grip:Connection>
      <grip:Output step="0" socket="0" previewed="true"/>
      <grip:Input step="2" socket="0"/>
    </grip:Connection>
    <grip:Connection>
      <grip:Output step="1" socket="0" previewed="false"/>
      <grip:Input step="2" socket="1"/>
    </grip:Connection>
    <grip:Connection>
      <grip:Output source="0" socket="0" previewed="false"/>
      <grip:Input step="0" socket="0"/>
    </grip:Connection>
    <grip:Connection>
      <grip:Output source="1" socket="0" previewed="false"/>
      <grip:Input step="1" socket="0"/>
    </grip:Connection>
  </connections>
  <settings>
    <teamNumber>0</teamNumber>
    <publishAddress>roborio-0-frc.local</publishAddress>
    <deployAddress>roborio-0-frc.local</deployAddress>
    <deployDir>/home/lvuser</deployDir>
    <deployUser>lvuser</deployUser>
    <deployJavaHome>/usr/local/frc/JRE/</deployJavaHome>
    <deployJvmOptions>-Xmx50m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError</deployJvmOptions>
  </settings>
</grip:Pipeline>
```

### CODE REVIEW

**Comment by SamCarlberg** [comment]
@JLLeitschuh Are you planning on doing any more with this?

**Comment by JLLeitschuh** [comment]
I think this was shot down as impractical. Requires tuning the cameras. This only works because the sample images are configured to work.
I don't know how this could be practical on a robot.

Thoughts?

**Comment by SamCarlberg** [comment]
It doesn't need to be practical on a robot since this isn't an FRC-specific program like the SmartDashboard or RobotBuilder. What kind of tuning do the cameras need? I assume same exposure settings, anything else?

**Comment by JLLeitschuh** [comment]
I really have no idea.
If you'd like to explore this further be my guest.

**Comment by AustinShalit** [comment]
This PR has grown stale.  Please reopen with updates and we will take another look.

**Pull request closed without merging**
