### PR TITLE
Creates expanding input socket lists for large operations

### PR DESCRIPTION
**Pull request by osulacam**
This makes the ui much easier to use for filter contours and a few other large operations.

### CODE REVIEW

**Comment by AustinShalit** [comment]
Can you please paste a photo?

**Comment by osulacam** [comment]
screen shot 2016-07-21 at 4 09 52 pm
screen shot 2016-07-21 at 4 10 35 pm

**Comment by AustinShalit** [comment]
Nice! A few things:
- Can you make it dynamic? I have a really big display so the steps no longer use the full hight of the pipeline.
- Weird visual things happen when you collapse a section that has a connection in it (see photo)
- For some reason NTManager spams the console now.

untitled

**Comment by JLLeitschuh** [comment]
Uuuuuuuuhhhhh... I'm not sure that this is the route that I would have taken to fix this UI problem.
I feel like there's a better way. I don't know what that is though.

**Comment by osulacam** [comment]
I'm not that experiencde with javafx so I wouldn't be surprised if there was an easier way to do this. Brad really wanted this to get fixed and I defiantly agree that it was making the UI much more difficult to use.
I'll take a look and try to fix the issues that Austin brought up.

**Comment by AustinShalit** [comment]
This is related to #413.  Maybe we go that (413's) route?

**Comment by AustinShalit** [comment]
This is related to #327

**Comment by osulacam** [comment]
I created a new pull request that implements the suggestion from that issue better. I felt like that way was a bit cleaner overall.

**Pull request closed without merging**
