### PR TITLE
Add AdvancedFilterCountoursOperation

### PR DESCRIPTION
**Pull request by drbobbob**
Fixes issue #441

### CODE REVIEW

**Comment by drbobbob** [comment]
I would like to write tests for this feature but I am not quite sure where to put them.

**Comment by ThomasJClark** [comment]
Looks good.  Do you wanna just add these parameters to the regular FilterContoursOperation?

**Comment by drbobbob** [comment]
I certainly can.  Just let me know what you would like me to do.

**Comment by ThomasJClark** [comment]
Nice!  Just a few notes:

- "Min Vertex Count" and "Max Vertex Count" get cut off because they're too long.  They could be renamed to "Min Vertices" and "Max Verticies"
- Max vertices should have a much higher initial value (like 1000000), so it shouldn't actually filter anything by default.
- "Force convex" can be removed, since solidity does the same thing (100% solidity === convex)

**Pull request merged**
