### PR TITLE
Fixes Erode and Dilate so they work with the new Optional

### PR DESCRIPTION
**Pull request by JLLeitschuh**

### CODE REVIEW

**Comment by ThomasJClark** [comment]
Find Min and Max is also broken

**Comment by JLLeitschuh** [comment]
Fine. Merge this. I'll open another PR.

**Comment by JLLeitschuh** [comment]
Wait, which operation?

**Comment by ThomasJClark** [comment]
Fix it in this PR.  It's the same issue.

**Comment by ThomasJClark** [comment]
Nevermind, you already opened a second pr

**Pull request merged**
