### PR TITLE
Change source selector to a dropdown.

### PR DESCRIPTION
**Pull request by AustinShalit**
This is make the sources box cleaner.   ~~Anyone know why there is a null pointer error in the test?~~

untitled

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Looks sooo nice!!! 👍

**Comment by AustinShalit** [comment]
There are still buttons on the dialog pane

**Comment by AustinShalit** [comment]
I solved the test failure and also made a style change to remove the redundant word "add".

untitled

**Comment by JLLeitschuh** [comment]
This G2G?

**Comment by AustinShalit** [comment]
Yes

**Pull request merged**
