### PR TITLE
Update xstream version to 1.4.10 to fix security issue

### PR DESCRIPTION
**Pull request by JLLeitschuh**
[//]: # (Please ensure that the "Allow edits from maintainers" checkbox is checked. Thanks!)

### CODE REVIEW

**Comment by SamCarlberg** [comment]
What security issue?

**Comment by JLLeitschuh** [comment]
It should basically make our version eye badge no longer show "insecure".
https://www.versioneye.com/java/com.thoughtworks.xstream:xstream/1.4.9

**Comment by AustinShalit** [comment]
Change log for reference: http://x-stream.github.io/changes.html

Will test when I get home

**Comment by JLLeitschuh** [comment]
I can't merge this without one person's approval. (I mean I can if I want to disable the setting) but I don't want to.

**Pull request merged**
